server:
  port: 8083
spring:
  application:
    name: service3
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        healthCheckPath: /health-check
        healthCheckInterval: 20s
  datasource:
    url: jdbc:h2:file:./entity3_db
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
