server:
  port: 8081
spring:
  application:
    name: service1
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        healthCheckPath: /health-check
        healthCheckInterval: 20s
  datasource:
    url: jdbc:h2:file:./entity1_db
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
